# -*- coding: utf-8 -*-
"""Python_Intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWCV7PI3zw166v4fsYDj6BSPBmRRuvVF
"""

# bool, int, float, str
a = 'Data Science'
print(a)
type(a)

type(a)

z = True
type(z)

# bool -> int -> float -> str
True + 6 + 7.5
#1+6+7.5

bool(0)

#Auto typecasting
True + 3 + int(4.5)

a = 3
b= 4.5
print(type(a))
print(type(b))

a + int(b)

3 + int('4')

# true -> 1, false -> 0
False + 4

"""1. int(): Practice"""

int(123.987)

int(10+5j)

int(True)

int(False)

int("10")

int("10.5")

int("ten")

int("0B1111")

"""2. float(): Practice"""

float(10)

float(10+5j)

float(True)

float(False)

float("10.5")

float("10")

float("ten")

float("0B1111")

"""3. bool(): Practice"""

bool(0)

bool(1)

bool(10)

bool(10.5)

bool(0.178)

bool(0.0)

bool(10-2j)

bool(0+0j)

bool("True")

bool("False")

bool("")

"""4. Slicing Practice"""

#slicing a list
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#slice from index 2 to index 6
slice_1 = my_list[2:6]
print(slice_1)

#slice from index 1 to the end
slice_2 = my_list[1:]
print(slice_2)

#slice from beginning to index 5
slice_3 = my_list[:5]
print(slice_3)

#slice of the list with a step size of 2
slice_4 = my_list[::2]
print(slice_4)

#slicing a string
my_string = "Hello, World!"

# slice string from index 7 to end
slice_5 = my_string[7:]
print(slice_5)

#slice from beginning to index 5
slice_6 = my_string[:5]
print(slice_6)

#slice with a step size of 2
slice_7 = my_string[::2]
print(slice_7)

#slicing with negative indices
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#slice list from second last element to end
slice_8 = my_list[-2:]
print(slice_8)

#slice from beginning to third to last element
slice_9 = my_list [:-3]
print(slice_9)

#slice list in reverse order
slice_10 = my_list[::-1]
print(slice_10)

"""5. Arithmetic Operators"""

x = 10 + 5
print(x)

y = 10 - 5
print(y)

z = 10 * 5
print(z)

w = 10 / 5
print(w)

mod = 10 % 3
print(mod)

exp = 10 ** 3
print(exp)

floor_div = 10 // 3
print(floor_div)

"""6. Assignment Operators"""

a = 5
a += 3
print(a)

b = 5
b -= 3
print(b)

c = 5
c *= 3
print(c)

d = 5
d /= 3
print(d)

e = 5
e%= 3
print(e)

f = 5
f **= 3
print(f)

g = 5
g //= 3
print(g)

"""7. Comparison Operators"""

x = 5
y = 10
print(x == y)

print(x!=y)

print(x > y)

print(x < y)

print(x >= y)

print(x <= y)

"""8. Logical Operators"""

a = True
b = False
print(a and b)

print(a or b)

print(not a)

"""9. Bitwise Operators"""

x = 10
y = 7

print(x & y)

print(x | y)

print(x ^ y)

print(~x)

print(x << 2)

print(x >> 2)